[build]
  publish = "dist"
  command = "npm install --ignore-scripts --legacy-peer-deps && npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--ignore-scripts --legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200